name: 'Build and publish docker action'
description: 'Build and publish docker action'
inputs:
  repositories: 
    description: 'Projects to execute on'
    required: true
  username: 
    description: 'Username'
    required: true
  password: 
    description: 'Password'
    required: true
  registry: 
    description: 'Registry'
    required: true
  tag: 
    description: 'Docker image tag'
    required: true
outputs:
  status:
    description: 'Status of execution'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repositories }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.registry }}
    - ${{ inputs.tag }}